### ISSUE TITLE
Card Images proposal

### ISSUE THREAD

**Issue by jamieadkins95** [GwentCommunityDevelopers/gwent-data#10]
Currently, when we receive new images from CDPR, I run a script to organise them and to produce the various sizes (thumbnail, low, medium, high). I then upload them to my cloud storage bucket.

I don't transform the images in any other way. This means that the images maintain that odd transparent border (e.g. [Geralt](https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Fv0-9-10%2F112103%2F11210300%2Fhigh.png?alt=media&token=8a73f38d-7344-4757-984f-bb46e6d85a31)).

Would it be better if the images had that border removed (e.g. [Geralt](https://firebasestorage.googleapis.com/v0/b/gwent-9e62a.appspot.com/o/images%2Ftest%2Fhigh.png?alt=media))? 

I have a script that is able to do it, it's just a question of if that is the correct thing to do.

Thoughts @Zolmeister @Tri125 ?

**Comment by jamieadkins95** [comment]
It would mean a slight change to the card data structure. At the moment we have 5 image qualities: `original`, `high`, `medium`, `low`, `thumbnail`. I would like to add `ultra` to this list. `original` would become the raw image from CDPR that has not been transformed and `ultra` would be the same resolution as `original` but with the excess transparency removed.

**Comment by Zolmeister** [comment]
I am against changing the images again (0.7-0.8? the space was reduced), and also against having an image quality different from the rest. My reason is simply that it would mean a significant update in card-image handling on my end.

That said I do think no-space is technically better, so perhaps in `1.0` (breaking changes) all images could be cropped.

**Comment by jamieadkins95** [comment]
The last major change was a change in the images that CDPR gave me.

Saving this change for the full release of Gwent is a sensible suggestion

**Comment by Tri125** [comment]
Aye aye. I'm with Zol. I just dump the images but people consuming the images expect a certain size. They already have style for their work and CSS is a merciless god. I'd also prefer that they are just different size, not different crop.

**Comment by jamieadkins95** [comment]
Ok I'll save this for the full release of Gwent. I have the script ready, I just have to enable it at the time.

Is the suggestion that when we do make the change, we stick with `original`, `high`, `medium`, `low`, `thumbnail`, but just with cropped borders for all of them?
If I'm honest, I would like the original source image stored somewhere, in case it is useful to someone.

**Comment by Zolmeister** [comment]
Yes (all same size though, some cards have smaller corner flare)
If you really want, document the padding distance. If someone wants to go through the trouble of using the original they'll have to resize the images anyways and can re-add the padding.
