### ISSUE TITLE
Isn't data_definitions encrypted?

### ISSUE THREAD

**Issue by tianyuLong** [GwentCommunityDevelopers/gwent-data#22]
Please tell me how to unzip data_definitions without a password? Thank you 👍

**Comment by Tri125** [comment]
Hello and thank you for your interest in the project.

You are correct that the game file is encrypted. It is up to you to make sure that you legally obtained the game file and the password to decrypt it.  Should you attempt to circumvent the protection on the file against your local law, we shall not be held responsible for your actions.

If you are interested in the latest card data in the standardized json format you can find it in the releases for [gwent-data-release](https://github.com/GwentCommunityDevelopers/gwent-data-release/releases).
