### ISSUE TITLE
missing artist information

### ISSUE THREAD

**Issue by appdevrs** [GwentCommunityDevelopers/gwent-data#28]
this project enables so much to the Gwent community, thank you for creating it.

From what I can see, the artwork artistname seems to be the only information missing in the json.
Is there a way to get those data?

or am I missing a way to use the ingameArtId to fetch the artist data?

**Comment by jamieadkins95** [comment]
Hey,

The card-data files within Gwent no longer contain any artist information, so we can't extract it and put it in the JSON. Have a look at a card in game, CDPR don't list the artist anymore.

**Comment by appdevrs** [comment]
Hi,

I didn't know that it wasn't even ingame anymore.
Somehow strange since CDPR told me to credit the artists if I use the images.
(Does that mean I don't have to anymore, too?)

I guess this already closes the issue.
