### ISSUE TITLE
Image compression

### ISSUE THREAD

**Issue by kachna96** [GwentCommunityDevelopers/gwent-data#29]
Hi,
have you ever thought about compressing the images for example through https://tinypng.com/ ?
You can reduce the image size by 50-60% without noticeable difference which is very useful when you're developing a website/webapp.

Anyway, keep up the good work!

**Comment by jamieadkins95** [comment]
CDPR are kind enough to supply us with the card images. The goal of this project is to provide raw data to developers, so you can populate your own databases/apis with whatever data structure you want. The same idea can be applied to the card images. We would like to supply the raw images to developers, and if you want to tinypng them and rehost them for your projects, then you are more than welcome to do that.

**Comment by kachna96** [comment]
thanks :)

**Comment by jamieadkins95** [comment]
Be sure to follow [CDPR's fan content guidelines](https://www.playgwent.com/en/fan-content)
