### ISSUE TITLE
Mulligan Update

### ISSUE THREAD

**Issue by jamieadkins95** [GwentCommunityDevelopers/gwent-data#33]
Some changes to how Leaders work:

https://www.playgwent.com/en/news/25285/mulligan-update-is-live

- Leaders now affect Recruit Cap. Base value for all decks is 150.

Will update gwent-data on 12th Jan. Unfortunately, I'm busy until then.

**Comment by teddybee-r** [comment]
I have no python experience. But the error was enough to point me to things
I was able to create an output file.

> Creating card data JSON...
Traceback (most recent call last):
  File "E:\Gwent\v1.1.0\gwent-data-master\gwent.py", line 47, in <module>
    cardsJson = CardData.create_card_json(gwentDataHelper, PATCH)
  File "E:\Gwent\v1.1.0\gwent-data-master\CardData.py", line 97, in create_card_json
    card['mulligans'] = int(template.find('Mulligans').text)
AttributeError: 'NoneType' object has no attribute 'text'

in CardData.py I changed line 96/97       

This is for backwards compatibility (anyone who used the mulligan field to display the mulligan value on layered cards. I can use this to update my database without changing code)
 ```
if (tier == LEADER):
            card['mulligans'] = int(template.find('Provision').text)
```

this is the output.
[compatibility.zip](https://github.com/GwentCommunityDevelopers/gwent-data/files/2745658/compatibility.zip)

here is another one where I just deleted the lines (this will delete the mulligan field in the cards.json)
[no-mull.zip](https://github.com/GwentCommunityDevelopers/gwent-data/files/2745683/no-mull.zip)

Here is a compare of v1.0.1.26 // v1.1.0 Templates.xml
![image](https://user-images.githubusercontent.com/15222466/50974209-fa8da380-14ea-11e9-95d1-a2464e3e17c7.png)


this is the data_definitions file of v1.1.0
[data_definitions.zip](https://github.com/GwentCommunityDevelopers/gwent-data/files/2745690/data_definitions.zip)

Cheers.

**Comment by jamieadkins95** [comment]
Great, thanks!

I'll make a PR on Saturday to formalise this change. I think for backwards compatibility I'll set mulligans to always be `0` and add a new field called provisionsBoost.

I'm still haven't settled on how v2 of gwent-data will look (difficult when they make breaking changes to the game 😢). I'll remove the `mulligans` field  from that.

**Comment by jamieadkins95** [comment]
https://github.com/GwentCommunityDevelopers/gwent-data-release/releases/tag/v1.1.0-no-images

Card data update. Still waiting on card images from CDPR

**Comment by jamieadkins95** [comment]
https://github.com/GwentCommunityDevelopers/gwent-data-release/releases/tag/v1.1.0
