### ISSUE TITLE
v6.1 Tribute & Hoard

### ISSUE THREAD

**Issue by teddybee-r** [GwentCommunityDevelopers/gwent-data#38]
Hey I am sad to hear that you will be discontinuing Roach.
This will also probably mean you will discontinue to work on this which is quite sad because I cannot fix the errors which came with v6.1

It is only a minor error though and maybe you can help me/us out in terms of fixing it.

Sadly I don't know python but I understand some basics where to look at.

CDPR changed Tribute and Hoard to dynamic values (when a leader is selected which reduces the values).

The old patch used {Tribute} in the localization files while the new one uses {Tribute-B.P.BB_Tribute}
The same is for {Hoard}.

old / new
{Hoard}     {Hoard-B.P.BB_Hoard}
{Hoard2}   {Hoard2-B.P.BB_Hoard}
{Hoard3}   {Hoard3-B.P.BB_Hoard}

If I understand it correctly this happens in GwentUtils.py starting at line 50?

**Comment by jamieadkins95** [comment]
Hey, yeah I this repo is deprecated too. I'm happy to review PRs, and I'll look into this issue tonight, might not be as prompt for any future issues though

**Comment by jamieadkins95** [comment]
Have fixed with a quick string replacement :)

**Comment by teddybee-r** [comment]
Thanks for the help but I believe this would be correct to account for Hoard Hoard2 Hoard3
`tooltips[card_id] = tooltips[card_id].replace("-B.P.BB_Hoard", "")`

unless you cannot replace it with something empty.

only https://gwent.one/en/card/202555 uses it.

Cheers

**Comment by jamieadkins95** [comment]
Ah oops, I didn't realise there was Hoard2, will fix
