### ISSUE TITLE
Bold text in card ability

### ISSUE THREAD

**Issue by Zolmeister** [GwentCommunityDevelopers/gwent-data#5]
Card info in-game has specific bolding applied to it which is stripped out. Some way to preserve that formatting (either in-line, or an offset-length style mapping) would be better.

e.g.
```js
info: {'en-US': 'Deploy'},
infoStyle: {0: '<b>', 6: '</b>'}
```
to apply it, something like:
```coffee
infoArr = info.split('')
_.map _.orderBy(_.keys(infoStyle), ['desc']), (offset) ->
  infoArr.splice offset, 0, infoStyle[offset]
info infoArr.join('')
```

**Comment by Tri125** [comment]
I think the json should contain the data but be extra careful for any sort of font formatting. Font formatting is something that an application that use the data should handle the way they want. If we format at the source (gwent-data) then everyone downstream has to work against the pre-established format to make it the way they want.

Although I would also prefer having the mechanism in bold, the HTML works fine to display on a website but if we consider something like WPF or ASP (among others) you can't just take the data as the b tag will be displayed as text.

Of course, ``\n`` is already there but it doesn't suffer the same problem, it's widely interpreted as being a newline character and I think the vast majority would prefer a newline separating mechanism from text anyways.

Thoughts?

**Comment by jamieadkins95** [comment]
It's an interesting problem. I agree that we should not force formatting onto users, but also at the same time  I don't like that the formatting information is missing from the data set.

A mapping is one way to solve that, but then again we need to cater for localisations.

Another option would be to provide 2 fields in the data set, one that includes the formatting, and one that strips it out.

i.e.

`'info': { 'en-US': 'Some card description without formatting' }`

`'infoFormatted': { 'en-US': 'Some card description with formatting' }`

**Comment by Tri125** [comment]
Sounds good to me.

**Comment by jamieadkins95** [comment]
#7 added a new field called `infoRaw` that preserves all of the formatting that is in the raw files.
